
services:
  db:
    image: postgres:latest
    container_name: movieapi
    environment:
      POSTGRES_USER: movieapi
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movieapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  
  