
services:
  postgres:
    image: postgres:lastest
    container_name: movieapi
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: