spring:
  application:
  name: movieapi

  datasource:
    url: jdbc:postgresql://localhost:5432/movieapi
    username: movieapi
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  
  
  flyway:
    enabled: true
    
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html
    
movieapi:
  security:
    secret: "kkasirmdsciurmdp12312321635g58saAAsd"