spring:
  application:
    name: movieapi

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

movieapi:
  security:
    secret: "${JWT_SECRET}"

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    access-token: ${TMDB_TOKEN}
